// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct AuthInputContent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static AuthInputContent GetRootAsAuthInputContent(ByteBuffer _bb) { return GetRootAsAuthInputContent(_bb, new AuthInputContent()); }
  public static AuthInputContent GetRootAsAuthInputContent(ByteBuffer _bb, AuthInputContent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AuthInputContent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int LastInputHostReceivedFromYou { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MsAheadOfAvgPlayer { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int FramesStart { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public Messages.ByteArray? Frames(int j) { int o = __p.__offset(10); return o != 0 ? (Messages.ByteArray?)(new Messages.ByteArray()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int FramesLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Messages.AuthInputContent> CreateAuthInputContent(FlatBufferBuilder builder,
      int lastInputHostReceivedFromYou = 0,
      int msAheadOfAvgPlayer = 0,
      int framesStart = 0,
      VectorOffset framesOffset = default(VectorOffset)) {
    builder.StartTable(4);
    AuthInputContent.AddFrames(builder, framesOffset);
    AuthInputContent.AddFramesStart(builder, framesStart);
    AuthInputContent.AddMsAheadOfAvgPlayer(builder, msAheadOfAvgPlayer);
    AuthInputContent.AddLastInputHostReceivedFromYou(builder, lastInputHostReceivedFromYou);
    return AuthInputContent.EndAuthInputContent(builder);
  }

  public static void StartAuthInputContent(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddLastInputHostReceivedFromYou(FlatBufferBuilder builder, int lastInputHostReceivedFromYou) { builder.AddInt(0, lastInputHostReceivedFromYou, 0); }
  public static void AddMsAheadOfAvgPlayer(FlatBufferBuilder builder, int msAheadOfAvgPlayer) { builder.AddInt(1, msAheadOfAvgPlayer, 0); }
  public static void AddFramesStart(FlatBufferBuilder builder, int framesStart) { builder.AddInt(2, framesStart, 0); }
  public static void AddFrames(FlatBufferBuilder builder, VectorOffset framesOffset) { builder.AddOffset(3, framesOffset.Value, 0); }
  public static VectorOffset CreateFramesVector(FlatBufferBuilder builder, Offset<Messages.ByteArray>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateFramesVectorBlock(FlatBufferBuilder builder, Offset<Messages.ByteArray>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartFramesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Messages.AuthInputContent> EndAuthInputContent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Messages.AuthInputContent>(o);
  }
};


}
