// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages
{

public enum GameMessageType : sbyte
{
  JoinGame = 0,
  PlayerInput = 1,
  AuthInput = 2,
  P2PSyncContent = 3,
  PingRequest = 4,
  PingResponse = 5,
};


}
