// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct JoinGameMsgContent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static JoinGameMsgContent GetRootAsJoinGameMsgContent(ByteBuffer _bb) { return GetRootAsJoinGameMsgContent(_bb, new JoinGameMsgContent()); }
  public static JoinGameMsgContent GetRootAsJoinGameMsgContent(ByteBuffer _bb, JoinGameMsgContent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JoinGameMsgContent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Slot { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Messages.JoinGameMsgContent> CreateJoinGameMsgContent(FlatBufferBuilder builder,
      int slot = 0) {
    builder.StartTable(1);
    JoinGameMsgContent.AddSlot(builder, slot);
    return JoinGameMsgContent.EndJoinGameMsgContent(builder);
  }

  public static void StartJoinGameMsgContent(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddSlot(FlatBufferBuilder builder, int slot) { builder.AddInt(0, slot, 0); }
  public static Offset<Messages.JoinGameMsgContent> EndJoinGameMsgContent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Messages.JoinGameMsgContent>(o);
  }
};


}
