// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct JoinLobbyMsgContent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static JoinLobbyMsgContent GetRootAsJoinLobbyMsgContent(ByteBuffer _bb) { return GetRootAsJoinLobbyMsgContent(_bb, new JoinLobbyMsgContent()); }
  public static JoinLobbyMsgContent GetRootAsJoinLobbyMsgContent(ByteBuffer _bb, JoinLobbyMsgContent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JoinLobbyMsgContent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string PlayerName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPlayerNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetPlayerNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetPlayerNameArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Messages.JoinLobbyMsgContent> CreateJoinLobbyMsgContent(FlatBufferBuilder builder,
      StringOffset playerNameOffset = default(StringOffset)) {
    builder.StartTable(1);
    JoinLobbyMsgContent.AddPlayerName(builder, playerNameOffset);
    return JoinLobbyMsgContent.EndJoinLobbyMsgContent(builder);
  }

  public static void StartJoinLobbyMsgContent(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPlayerName(FlatBufferBuilder builder, StringOffset playerNameOffset) { builder.AddOffset(0, playerNameOffset.Value, 0); }
  public static Offset<Messages.JoinLobbyMsgContent> EndJoinLobbyMsgContent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Messages.JoinLobbyMsgContent>(o);
  }
};


}
