// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct LoadGameMsgContent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static LoadGameMsgContent GetRootAsLoadGameMsgContent(ByteBuffer _bb) { return GetRootAsLoadGameMsgContent(_bb, new LoadGameMsgContent()); }
  public static LoadGameMsgContent GetRootAsLoadGameMsgContent(ByteBuffer _bb, LoadGameMsgContent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LoadGameMsgContent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string JoinCode { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetJoinCodeBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetJoinCodeBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetJoinCodeArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Messages.LoadGameMsgContent> CreateLoadGameMsgContent(FlatBufferBuilder builder,
      StringOffset joinCodeOffset = default(StringOffset)) {
    builder.StartTable(1);
    LoadGameMsgContent.AddJoinCode(builder, joinCodeOffset);
    return LoadGameMsgContent.EndLoadGameMsgContent(builder);
  }

  public static void StartLoadGameMsgContent(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddJoinCode(FlatBufferBuilder builder, StringOffset joinCodeOffset) { builder.AddOffset(0, joinCodeOffset.Value, 0); }
  public static Offset<Messages.LoadGameMsgContent> EndLoadGameMsgContent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Messages.LoadGameMsgContent>(o);
  }
};


}
