// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages
{

public enum LobbyMessageType : sbyte
{
  HostConnectAck = 0,
  JoinLobby = 1,
  JoinLobbyResponse = 2,
  PlayerJoinedLobby = 3,
  LoadGame = 4,
  JoinGameAck = 5,
  StartGame = 6,
};


}
